spring:
  datasource:
    url: jdbc:hsqldb:logs:db/log
    username: log
    password: logpass
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.batch_size: 100
#        format_sql: true
#    show-sql: true

#logging:
#  level:
#    root: off
#    jdbc.sqlonly: info

log:
  file: logs.json
  flag:
    time: 4